### ISSUE TITLE
Giphy: Build the description section to describe the the giphy plugin

### ISSUE THREAD

**Issue by Johndiddles** [zurichat/zc_plugin_tools#295]
This is the section of the description page that contains the text that properly describes the plugin and what it does

**Comment by Oyedolacode** [comment]
Live link: https://zc-plugin-tools-oyedolacode.vercel.app/
PR:https://github.com/zurichat/zc_plugin_tools/pull/445
Figma: https://www.figma.com/file/fYCR0EUcqSe5OlG9G38GxI/Team-Hobbes-Company-Online-Tool-Plugin?node-id=2550%3A12989

**Comment by Oyedolacode** [comment]
PR Link: https://github.com/zurichat/zc_plugin_tools/pull/445

**Comment by Oyedolacode** [comment]
![Uploading Screenshot_20210905-125324.png…]()
