### ISSUE TITLE
Gmail - [DESIGN ISSUE] - Design the layout for the Gmail plugin

### ISSUE THREAD

**Issue by Evavic44** [zurichat/zc_plugin_tools#311]
### Comments or additional Information
This is the page you see when the user clicks the gmail plugin.

**Comment by BKINBU** [comment]
Slack Name: 'SAYO

Figma :   @@[https://www.figma.com/file/fYCR0EUcqSe5OlG9G38GxI/Team-Hobbes%3A-Company-Online-Tool-Plugin?node-id=1484%3A8126](url)

**Comment by BKINBU** [comment]
Slack Name : 'SAYO

Figma Link : https://www.figma.com/file/fYCR0EUcqSe5OlG9G38GxI/Team-Hobbes%3A-Company-Online-Tool-Plugin?node-id=1484%3A8126
